import type { Metadata } from "next";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { playfair_display, raleway } from "@/constants/fonts";
import { Theme } from "@radix-ui/themes";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${raleway.className} body-style! antialiased`}>
        <Theme>
          <div className="w-full  ">{children}</div>
        </Theme>
      </body>
    </html>
  );
}
